# Generated by Django 5.1.4 on 2025-02-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_created_on_faq_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
