# Generated by Django 5.1.4 on 2025-01-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_comment_review_review_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
    ]
