# Generated by Django 5.1.4 on 2025-05-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_review_comment_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
